# -*- coding: utf-8 -*-
"""expense_Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JOR51lnB3_ToZXutMvC7hjZQrJH2W_NG
"""

import csv
from datetime import datetime

def add_expense(category, description, amount):
    with open('expenses.csv', 'a', newline='') as file:
        writer = csv.writer(file)
        date = datetime.now().strftime('%Y-%m-%d')
        writer.writerow([date, category, description, amount])
    print("Expense added successfully.")

def view_expenses():
    try:
        with open('expenses.csv', 'r') as file:
            reader = csv.reader(file)
            for row in reader:
                print(row)
    except FileNotFoundError:
        print("No expenses found.")

def calculate_total_expenses():
    total = 0
    try:
        with open('expenses.csv', 'r') as file:
            reader = csv.reader(file)
            next(reader)  # Skip header row
            for row in reader:
                total += float(row[3])
    except FileNotFoundError:
        print("No expenses found.")
    return total

def view_expenses_by_category(category):
    try:
        with open('expenses.csv', 'r') as file:
            reader = csv.reader(file)
            print(f"Expenses for {category}:")
            for row in reader:
                if row[1].lower() == category.lower():
                    print(row)
    except FileNotFoundError:
        print("No expenses found.")

def check_budget(budget):
    total = calculate_total_expenses()
    if total > budget:
        print(f"Warning: You have exceeded your budget! Total expenses: {total}")
    else:
        print(f"You're within budget. Total expenses: {total}")

def menu():
    while True:

        name = input("\n Enter your name : ").strip()
        print("<--------", name,"'s expenses----->"   )
        print("\n--- Expense Tracker Menu ---")
        print("1. Add an Expense")
        print("2. View All Expenses")
        print("3. View Expenses by Category")
        print("4. Calculate Total Expenses")
        print("5. Set Budget and Check")
        print("6. Exit")

        choice = input("Enter your choice: ").strip()

        if choice == '1':
            category = input("Enter category(food, transport, shopping, other): ").strip()
            description = input("Enter description(time/type): ").strip()
            amount = float(input("Enter amount: ").strip())
            add_expense(category, description, amount)

        elif choice == '2':
            view_expenses()

        elif choice == '3':
            category = input("Enter category(food, transport, shopping, other): ").strip()
            view_expenses_by_category(category)

        elif choice == '4':
            total = calculate_total_expenses()
            print(f"Total expenses: {total}")

        elif choice == '5':
            budget = float(input("Enter your budget: ").strip())
            check_budget(budget)

        elif choice == '6':
            print("Exiting... Goodbye!")
            break

        else:
            print("Invalid choice. Please try again.")

# Run the menu
menu()